import type { Metadata } from "next";
import { Geist, Instrument_Serif } from "next/font/google";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";


const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${bricolageGrotesque.variable} antialiased`}>{children}</body>
    </html>
  );
}
